// Copyright Seong Woo Lee. All Rights Reserved.

#ifndef RHI_ENUM_H
#define RHI_ENUM_H


#define RHI_MAX_BACK_BUFFERS            3
#define RHI_MAX_COLOR_ATTACHMENTS       8
#define RHI_MAX_32BIT_PUSH_CONSTANTS    32

#define RHI_ALL_MIPS                0xffffffff
#define RHI_ALL_LAYERS              0xffffffff


struct RHI_Device;
struct RHI_Command_Buffer;
struct RHI_Pass;
struct RHI_Buffer;
struct RHI_Buffer_Desc;
struct RHI_Buffer_View;
struct RHI_Buffer_View_Desc;
struct RHI_Texture;
struct RHI_Texture_Desc;
struct RHI_Texture_View;
struct RHI_Texture_View_Desc;
struct RHI_Sampler;
struct RHI_Sampler_Desc;
struct RHI_Heap;
struct RHI_Surface;
struct RHI_Surface_Desc;
struct RHI_Semaphore;
struct RHI_Pipeline;
struct RHI_Pipeline_Desc;
struct RHI_Box;


typedef u8 RHI_Command_Type;
enum {
    RHI_COMMAND_TYPE_GRAPHICS,
    RHI_COMMAND_TYPE_COMPUTE,
    RHI_COMMAND_TYPE_TRANSFER,

    RHI_COMMAND_TYPE_COUNT
};

enum RHI_Memory_Type {
    RHI_MEMORY_INVALID = 0,

    RHI_MEMORY_GPU_ONLY,   // Suitable for the fastest GPU access.
    RHI_MEMORY_UPLOAD,     // Suitable for per-frame data upload to GPU.
    RHI_MEMORY_READBACK,   // Suitable for read back from GPU.
};

enum RHI_Resource_State {
    RHI_RESOURCE_STATE_COMMON,
    RHI_RESOURCE_STATE_VERTEX_AND_CONSTANT_BUFFER,
    RHI_RESOURCE_STATE_INDEX_BUFFER,
    RHI_RESOURCE_STATE_RENDER_TARGET,
    RHI_RESOURCE_STATE_UNORDERED_ACCESS,
    RHI_RESOURCE_STATE_DEPTH_WRITE,
    RHI_RESOURCE_STATE_DEPTH_READ,
    RHI_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE,
    RHI_RESOURCE_STATE_PIXEL_SHADER_RESOURCE,
    RHI_RESOURCE_STATE_INDIRECT_ARGUMENT,
    RHI_RESOURCE_STATE_COPY_DEST,
    RHI_RESOURCE_STATE_COPY_SOURCE,
    RHI_RESOURCE_STATE_RAYTRACING_ACCELERATION_STRUCTURE,
    RHI_RESOURCE_STATE_GENERIC_READ,
    RHI_RESOURCE_STATE_ALL_SHADER_RESOURCE,
    RHI_RESOURCE_STATE_PRESENT
};

enum RHI_Buffer_View_Type {
    RHI_BUFFER_VIEW_TYPE_INVALID = 0,

    RHI_BUFFER_VIEW_TYPE_RAW,
    RHI_BUFFER_VIEW_TYPE_STRUCTURED,
    RHI_BUFFER_VIEW_TYPE_CONSTANT,
};

enum RHI_Pipeline_Type {
    // We want pipeline type to be explicitly set.
    RHI_PIPELINE_TYPE_INVALID = 0, 

    RHI_PIPELINE_TYPE_GRAPHICS,
    RHI_PIPELINE_TYPE_COMPUTE,
};

// Sampler comparison (shadow map) sampling and depth testing.
enum RHI_Compare {
    RHI_COMPARE_ALWAYS,
    RHI_COMPARE_NEVER,

    RHI_COMPARE_EQUAL,
    RHI_COMPARE_NOT_EQUAL,

    RHI_COMPARE_LESS,
    RHI_COMPARE_LESS_EQUAL,

    RHI_COMPARE_GREATER,
    RHI_COMPARE_GREATER_EQUAL,
};

enum RHI_Topology {
    RHI_TOPOLOGY_INVALID = 0,

    RHI_TOPOLOGY_TRIANGLES,
    RHI_TOPOLOGY_LINES,
    RHI_TOPOLOGY_POINTS,
};

enum RHI_Blend_Factor {
    RHI_BLEND_FACTOR_INVALID = 0,

    RHI_BLEND_FACTOR_ZERO,
    RHI_BLEND_FACTOR_ONE,

    RHI_BLEND_FACTOR_SRC_COLOR,
    RHI_BLEND_FACTOR_ONE_MINUS_SRC_COLOR,
    RHI_BLEND_FACTOR_DST_COLOR,
    RHI_BLEND_FACTOR_ONE_MINUS_DST_COLOR,

    RHI_BLEND_FACTOR_SRC_ALPHA,
    RHI_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA,
    RHI_BLEND_FACTOR_DST_ALPHA,
    RHI_BLEND_FACTOR_ONE_MINUS_DST_ALPHA,
};

enum RHI_Blend_Op {
    RHI_BLEND_OP_INVALID = 0,

    RHI_BLEND_OP_ADD,
    RHI_BLEND_OP_SUBTRACT,
    RHI_BLEND_OP_SUBTRACT_REVERSE,
    RHI_BLEND_OP_MIN,
    RHI_BLEND_OP_MAX,
};

enum RHI_Fill_Mode {
    RHI_FILL_SOLID = 0,
    RHI_FILL_WIREFRAME,
};

enum RHI_Cull_Mode {
    RHI_CULL_NONE = 0,
    RHI_CULL_CW,
    RHI_CULL_CCW,
};

#endif // RHI_ENUM
