// Copyright Seong Woo Lee. All Rights Reserved.

#ifndef RHI_ENUM_H
#define RHI_ENUM_H


#define RHI_MAX_BACK_BUFFERS        3
#define RHI_MAX_COLOR_ATTACHMENTS   8
#define RHI_SURFACE_FORMAT          RHI_TEXTURE_FORMAT_RGBA8_UNORM

#define RHI_ALL_MIP_LEVELS          0xffffffff
#define RHI_ALL_ARRAY_SLICES        0xffffffff
#define RHI_INFINITE                0xffffffff


struct RHI_Device;
struct RHI_Command_Buffer;
struct RHI_Pass;
struct RHI_Texture;
struct RHI_Texture_Desc;
struct RHI_Texture_View;
struct RHI_Texture_View_Desc;
struct RHI_Heap;
struct RHI_Surface;
struct RHI_Surface_Desc;
struct RHI_Semaphore;
struct RHI_Pipeline;
struct RHI_Pipeline_Desc;


typedef u8 RHI_Command_Type;
enum {
    RHI_COMMAND_TYPE_GRAPHICS,
    RHI_COMMAND_TYPE_COMPUTE,
    RHI_COMMAND_TYPE_TRANSFER,

    RHI_COMMAND_TYPE_COUNT
};

enum RHI_Resource_State {
    RHI_RESOURCE_STATE_COMMON,
    RHI_RESOURCE_STATE_VERTEX_AND_CONSTANT_BUFFER,
    RHI_RESOURCE_STATE_INDEX_BUFFER,
    RHI_RESOURCE_STATE_RENDER_TARGET,
    RHI_RESOURCE_STATE_UNORDERED_ACCESS,
    RHI_RESOURCE_STATE_DEPTH_WRITE,
    RHI_RESOURCE_STATE_DEPTH_READ,
    RHI_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE,
    RHI_RESOURCE_STATE_PIXEL_SHADER_RESOURCE,
    RHI_RESOURCE_STATE_INDIRECT_ARGUMENT,
    RHI_RESOURCE_STATE_COPY_DEST,
    RHI_RESOURCE_STATE_COPY_SOURCE,
    RHI_RESOURCE_STATE_RAYTRACING_ACCELERATION_STRUCTURE,
    RHI_RESOURCE_STATE_GENERIC_READ,
    RHI_RESOURCE_STATE_ALL_SHADER_RESOURCE,
    RHI_RESOURCE_STATE_PRESENT
};

enum RHI_Pipeline_Type {
    RHI_PIPELINE_TYPE_INVALID = 0,

    RHI_PIPELINE_TYPE_GRAPHICS,
    RHI_PIPELINE_TYPE_COMPUTE,
};

enum RHI_Compare_Op {
    RHI_COMPARE_OP_INVALID = 0,

    RHI_COMPARE_OP_NONE,
    RHI_COMPARE_OP_NEVER,
    RHI_COMPARE_OP_LESS,
    RHI_COMPARE_OP_EQUAL,
    RHI_COMPARE_OP_LESS_EQUAL,
    RHI_COMPARE_OP_GREATER,
    RHI_COMPARE_OP_NOT_EQUAL,
    RHI_COMPARE_OP_GREATER_EQUAL,
    RHI_COMPARE_OP_ALWAYS
};

enum RHI_Topology {
    RHI_TOPOLOGY_INVALID = 0,

    RHI_TOPOLOGY_TRIANGLES,
    RHI_TOPOLOGY_LINES,
    RHI_TOPOLOGY_POINTS,
};

enum RHI_Blend_Factor {
    RHI_BLEND_FACTOR_INVALID = 0,

    RHI_BLEND_FACTOR_ZERO,
    RHI_BLEND_FACTOR_ONE,

    RHI_BLEND_FACTOR_SRC_COLOR,
    RHI_BLEND_FACTOR_ONE_MINUS_SRC_COLOR,
    RHI_BLEND_FACTOR_DST_COLOR,
    RHI_BLEND_FACTOR_ONE_MINUS_DST_COLOR,

    RHI_BLEND_FACTOR_SRC_ALPHA,
    RHI_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA,
    RHI_BLEND_FACTOR_DST_ALPHA,
    RHI_BLEND_FACTOR_ONE_MINUS_DST_ALPHA,
};

enum RHI_Blend_Op {
    RHI_BLEND_OP_INVALID = 0,

    RHI_BLEND_OP_ADD,
    RHI_BLEND_OP_SUBTRACT,
    RHI_BLEND_OP_SUBTRACT_REVERSE,
    RHI_BLEND_OP_MIN,
    RHI_BLEND_OP_MAX,
};

enum RHI_Fill_Mode {
    RHI_FILL_MODE_SOLID,
    RHI_FILL_MODE_WIREFRAME,
};

enum RHI_Cull_Mode {
    RHI_CULL_MODE_NONE,
    RHI_CULL_MODE_FRONT,
    RHI_CULL_MODE_BACK,
};

#endif // RHI_ENUM
